# -*- coding: utf-8 -*-
"""EmotionSense-AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCkQp_bxpOVddW4orGcxETUoAVIBsKus
"""

!pip install transformers datasets torch evaluate --quiet

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate
import torch

# =====================================================
# 0) Install Dependencies
# =====================================================
!pip -q install transformers datasets evaluate accelerate

import numpy as np
import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import evaluate

# =====================================================
# 1) Load clean dataset (6 emotions, single label)
# =====================================================
ds = load_dataset("dair-ai/emotion")

train_ds = ds["train"]
val_ds   = ds["validation"]
test_ds  = ds["test"]

label_names = train_ds.features["label"].names
num_labels = len(label_names)
print("Labels:", label_names, "| num_labels:", num_labels)

# =====================================================
# 2) Tokenizer
# =====================================================
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

train_ds = train_ds.map(tokenize, batched=True)
val_ds   = val_ds.map(tokenize, batched=True)
test_ds  = test_ds.map(tokenize, batched=True)

cols = ["input_ids", "attention_mask", "label"]
train_ds = train_ds.remove_columns([c for c in train_ds.column_names if c not in cols]).with_format("torch")
val_ds   = val_ds.remove_columns([c for c in val_ds.column_names if c not in cols]).with_format("torch")
test_ds  = test_ds.remove_columns([c for c in test_ds.column_names if c not in cols]).with_format("torch")

# =====================================================
# 3) Model
# =====================================================
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

# =====================================================
# 4) Metrics
# =====================================================
accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy.compute(predictions=preds, references=labels)["accuracy"],
        "f1": f1.compute(predictions=preds, references=labels, average="weighted")["f1"]
    }

# =====================================================
# 5) Training Settings (no eval_strategy issues)
# =====================================================
training_args = TrainingArguments(
    output_dir="emotion-bert",
    num_train_epochs=2,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_steps=100,
    report_to="none"
)

# =====================================================
# 6) Trainer
# =====================================================
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics,
)

# =====================================================
# 7) Train
# =====================================================
trainer.train()

# =====================================================
# 8) Evaluate
# =====================================================
print("\n📊 Test Performance:")
print(trainer.evaluate(test_ds))

# =====================================================
# 9) Save Model
# =====================================================
model.save_pretrained("emotion_bert_model")
tokenizer.save_pretrained("emotion_bert_tokenizer")
print("\n✅ Model saved successfully at: emotion_bert_model/")

# =====================================================
# 10) Demo Prediction
# =====================================================
test_text = "I am very happy and excited today!"
inputs = tokenizer(test_text, return_tensors="pt")
with torch.no_grad():
    logits = model(**inputs).logits
pred = torch.argmax(logits, dim=1).item()

print("\n📝 Text:", test_text)
print("🎭 Predicted Emotion:", label_names[pred])

